import builtins from "builtin-modules";
import esbuild from "esbuild";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin. */`;

//──────────────────────────────────────────────────────────────────────────────

await esbuild
	.build({
		entryPoints: ["src/main.ts"],
		banner: { js: banner + "\n" },
		outfile: "main.js",
		bundle: true,
		external: [...builtins],
		format: "cjs",
		target: "es2022",
		sourcemap: false,
		minify: false,
		drop: ["debugger"],
		treeShaking: true,
		logLevel: "info",
		metafile: false,
	})
	.catch(() => process.exit(1));
